#### Universidad Autónoma de Aguascalientes
#### Departamento: Ciencias de la Computación
#### Carrera: Ingenieria en Computación Inteligente
#### Curso: Machine Learning y Deep Learning 
#### Maestro: Dr. Francisco Javier Luna Rosas

#### Alumno: Jorge Hernández
#### Semestre: Enero - Junio del 2025

##### PRACTICA No. 4. Redes Neuronales(SCIKIT-LEARN_MLPClassifier)
En esta práctica se implementará un modelo de clasificación una red neuronal con la técnica de propagación hacia atras (Por sus siglas en el idioma inglés NNBP). La red NNBP se implementará utilizando la libreria de código abierto SCIKIT-LEARN utilizando la clase MLPClassifier() 

Paso 1: Importar las librerías necesarias

In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

Paso 2: Cargamos el dataset

In [12]:
df_flor = pd.read_csv('../data/iris.csv', delimiter=";", decimal=".")
print(df_flor.head())
print(f"\nNumero de Muestras: {df_flor.shape[0]}\nNumero de Variables: {df_flor.shape[1]}")

   s.largo  s.ancho  p.largo  p.ancho    tipo
0      5.1      3.5      1.4      0.2  setosa
1      4.9      3.0      1.4      0.2  setosa
2      4.7      3.2      1.3      0.2  setosa
3      4.6      3.1      1.5      0.2  setosa
4      5.0      3.6      1.4      0.2  setosa

Numero de Muestras: 150
Numero de Variables: 5


PASO 3: Extraemos las variables predictoras.

In [13]:
x = df_flor.iloc[:,:4]
print(x[0:3])

   s.largo  s.ancho  p.largo  p.ancho
0      5.1      3.5      1.4      0.2
1      4.9      3.0      1.4      0.2
2      4.7      3.2      1.3      0.2


PASO 4: Ahora separamos la variable a predecir

In [14]:
y = df_flor.iloc[:,4:]
print(y.head())

     tipo
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa


PASO 5: Separamos los datos con el 70% de los datos para entrenamiento y el 30% para testing

In [15]:
xTrain, xTest, yTrain, yTest = train_test_split(x,y, train_size=0.7, random_state=0)

PASO 6: Mediante el constructor inicializa la instancia de red
Nota: Por defecto se usa 100 nodos en cada capa oculta, "solver" es el método de optimización

In [16]:
MLP_Classifier = MLPClassifier(learning_rate_init=0.01, max_iter=500)
print(MLP_Classifier)

MLPClassifier(learning_rate_init=0.01, max_iter=500)


PASO 7: Entrenamos el modelo llamando al método fit

In [17]:
MLP_Classifier.fit(xTrain,yTrain.iloc[:,0].values)

MLPClassifier(learning_rate_init=0.01, max_iter=500)

Paso 8: Imprimimos las predicciones en testing

In [18]:
print("Las predicciones en Testing son: \n")

valores_Predict = MLP_Classifier.predict(xTest)

print(f"Valor Real \t => Valor Predicho ")
print("=================================")

for i in range(len(xTest)):
    print(f"{yTest.values[i]} \t => {valores_Predict[i]} ")

Las predicciones en Testing son: 

Valor Real 	 => Valor Predicho 
['virginica'] 	 => virginica 
['versicolor'] 	 => versicolor 
['setosa'] 	 => setosa 
['virginica'] 	 => virginica 
['setosa'] 	 => setosa 
['virginica'] 	 => virginica 
['setosa'] 	 => setosa 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['virginica'] 	 => virginica 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['setosa'] 	 => setosa 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['setosa'] 	 => setosa 
['setosa'] 	 => setosa 
['virginica'] 	 => virginica 
['versicolor'] 	 => versicolor 
['setosa'] 	 => setosa 
['setosa'] 	 => setosa 
['virginica'] 	 => virginica 
['setosa'] 	 => setosa 
['setosa'] 	 => setosa 
['versicolor'] 	 => versicolor 
['versicolor'] 	 => versicolor 
['setosa'] 	 => setosa 
['virginica'] 	 => virginica 
['versicolor'] 	 => versicolor 
['setosa'] 

PASO 9: Calculamos los indices de calidad de la predicción

In [19]:
def indice_general(MC, nombres = None):
    precision_global = np.sum(MC.diagonal())/ np.sum(MC)
    error_global = 1 - precision_global
    precision_categorica = pd.DataFrame(MC.diagonal()/np.sum(MC,axis=1)).T
    if nombres != None:
        precision_categorica.columns = nombres
    return {"Matriz de Confusion:": MC,
            "Precisión Global": precision_global,
            "Error Global": error_global,
            "Precisión por Categoria": precision_categorica}

In [20]:
MC = confusion_matrix(yTest, valores_Predict)
indices = indice_general(MC, list(np.unique(y)))

for k in indices:
    print("\n%s: \n%s"%(k,str(indices[k])))


Matriz de Confusion:: 
[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]

Precisión Global: 
0.9777777777777777

Error Global: 
0.022222222222222254

Precisión por Categoria: 
   setosa  versicolor  virginica
0     1.0    0.944444        1.0
